# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ata_piix" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "boxy/root";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "boxy/home";
      fsType = "zfs";
    };

  # swapDevices = [{device = "/dev/zvol/boxy/swap";}];

  nix.maxJobs = lib.mkDefault 4;
}
