#!/bin/bash

# load all the env vars for this display
source "$MONITOR_BASE_FOLDER""/config.xinitrc"

# set the appropriate refresh rate and dpi
xrandr -r 144
xrandr --dpi 96x96

# set the background colour
xsetroot -solid "$BG_COLOUR" &

# load the conky monitor
exec xmonad
