#!/bin/bash

# load all the env vars for this display
source "$MONITOR_BASE_FOLDER""/config.xinitrc"

# set the proper dpi
xrandr --dpi 192x192

# set the background colour
xsetroot -solid "$BG_COLOUR" &

exec openbox
